[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_STORAGE_BUCKET,NEXT_PUBLIC_WHATSAPP_NUMBER,SMTP_USER"
